version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./gomoku-client
    environment:
      - REACT_APP_PROXY_HOST=http://server-app:8080
    volumes:
      - ./gomoku-client/src:/gomoku-client/src
      - ./gomoku-client/public:/gomoku-client/public
    ports:
      - 3000:3000
  server-app:
    build: ./gomoku-service
    environment:
      - dbURI=mongodb://mongo-db:27017
    volumes:
      - ./gomoku-service/src:/gomoku-service/src
    ports:
      - 8080:8080